apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::269599744150:role/eksNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
        - system:authenticated
  mapUsers: |
    - userarn: arn:aws:iam::269599744150:user/itadmin-terraform
      username: itadmin-terraform
      groups:
        - system:masters