apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
  namespace: devgitops
spec:
  metrics:
    - name: success-rate
      interval: 30s
      successCondition: result >= 0.95
      provider:
        prometheus:
          address: http://prometheus-server.monitoring:9090
          query: |
            sum(rate(http_requests_total{status=~"2.."}[1m]))
            /
            sum(rate(http_requests_total[1m]))