apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-alert-rules
  namespace: monitoring
spec:
  groups:
    - name: flask.rules
      rules:
        - alert: HighErrorRate
          expr: rate(http_requests_total{status="500"}[5m]) > 1
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High 500 error rate"