apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devgitops-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: devgitops
  endpoints:
    - port: http
      path: /metrics
      interval: 15s